version: 0.2

phases:
  pre_build:
    commands:
      - DOCKER_ID=${DOCKER_ID}
      - DOCKER_PASSWORD=${DOCKER_PASSWORD}
      - DOCKER_REPOSITORY=${DOCKER_REPOSITORY}
  build:
    commands:
      - echo  "$DOCKER_PASSWORD" | docker login -u  "$DOCKER_ID" --password-stdin
      - docker build -t $DOCKER_ID/DOCKER_REPOSITORY .
      - docker push $DOCKER_ID/DOCKER_REPOSITORY
